
files_path :
    model_path : ../src/models/xg_boost_model.joblib
    model_full_path : c:/Users/mayen/ML_DL_PROJECTS/Customer_Churn_prediction/src/model

    encoder_path :  ../models/encoder.joblib
    imputer_quant:  ../models/imputer_quant.joblib
    imputer_cat :  ../models/imputer_cat.joblib
    standardization :  ../models/standardisation.joblib  


