
files_path :
    model_path : ../src/models/xg_boost_model.joblib
    model_full_path : c:/Users/mayen/ML_DL_PROJECTS/Customer_Churn_prediction/src/models/xg_boost_model.joblib

    encoder_path :  ../src/models/encoder.joblib
    imputer_quant:  ../src/models/imputer_quant.joblib
    imputer_cat :  ../src/models/imputer_cat.joblib
    standardization :  ../src/models/standardisation.joblib  


